version: "3.4"
services:
  server:
    build: ./server
    image: "server.sourcify.public.dappnode.eth:0.1.0"
    ports:
      - "2000"
    volumes:
      - "repository:/home/data/repository"
    restart: always
  ui:
    build: ./ui
    image: "ui.sourcify.public.dappnode.eth:0.1.0"
    ports:
      - "1234"
    environment:
      - 'SERVER_URL=http://server.sourcify.public.dappnode'
      - 'REPOSITORY_URL=http://repository.sourcify.public.dappnode'
    restart: always
  repository:
    build: ./repository
    image: "repository.sourcify.public.dappnode.eth:0.1.0"
    ports:
      - "80"
    volumes:
      - "repository:/home/app/repository/"
    restart: always
volumes:
  repository: {}
