version: "3.4"
services:
  sourcify-server.public.dappnode.eth:
    build: ./build
    image: "sourcify-server.public.dappnode.eth:0.1.0"
    ports:
      - "2000"
    volumes:
      - "/usr/src/app/dnp_repo/sourcify-repository:/home/app/repository/"
    restart: always
